version: '3'
services:
    webserver:
        build: 
            context: ./bin/webserver
        container_name: 'php-webserver'
        restart: 'always'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www_host:/var/www:z
        links:
            - 'mariadb'
    mariadb:
        build: ./bin/mysql
        container_name: 'php-mariadb'
        volumes:
            - mariadb:/var/lib/mysql
        restart: 'always'
        ports:
            - "3306:3306"
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mariadb:
